package com.auditdocai.model;

import java.util.UUID;

public class ReportSection {
    private UUID id;
    private UUID reportId;    // AuditReport.id
    private String title;     // "Findings Summary"
    private String content;   // Rich text / Markdown generated by AI
    private int orderIndex;   // Section order

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public UUID getReportId() { return reportId; }
    public void setReportId(UUID reportId) { this.reportId = reportId; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }

    public int getOrderIndex() { return orderIndex; }
    public void setOrderIndex(int orderIndex) { this.orderIndex = orderIndex; }
}
